#+TITLE: Settings
#+AUTHOR: Lorenzo Cabrini
#+LANGUAGE: en
#+FILETAGS: :emacs:config:

This is my personal Emacs configuration. As most Emacs users, I maintain this 
as an org-mode file.

It is currently in a bit of a mess, but I'm working on cleaning it up. The 
section called =CLEAN UP= contains all the stuff that needs to be reviewed and 
put in the right location.

* Basics
** Personal Information
#+begin_src emacs-lisp
  (setq user-full-name "Lorenzo Cabrini"
        user-email-address "lorenzo.cabrini@gmail.com")
#+end_src

** Startup
Load up my index file on startup.

#+begin_src emacs-lisp
(setq initial-buffer-choice "~/org/index.org")
#+end_src

** Which Key
The [[https://github.com/justbur/emacs-which-key][which-key]] package is a neat little utility that shows possible completions
of a command.

#+BEGIN_SRC emacs-lisp
  (use-package which-key
    :ensure t
    :config
    (which-key-mode))
#+END_SRC
* User Interface
My user interface setup.

#+begin_src emacs-lisp
  (blink-cursor-mode 0)
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (global-hl-line-mode t)
#+end_src

** Icons

The [[https://github.com/domtronn/all-the-icons.el][all-the-icons]] package provides icons. You need to run the following the
install the required fonts:

#begin_example
  M-x all-the-icons-install-fonts
#+end_example

#+begin_src emacs-lisp
  (use-package all-the-icons)
#+end_src
** Theme
I normally prefer a blue theme, since it reminds me of the Amiga. However, I
also like to switch themes from time to time. 

*** Sanityinc Tomorrow Blue
This is my favorite theme and the one I use most of the time. ([[https://github.com/purcell/color-theme-sanityinc-tomorrow][GitHub]])

#+begin_src emacs-lisp
  ;; (use-package color-theme-sanityinc-tomorrow
  ;;   :ensure t
  ;;   :init
  ;;   (load-theme 'sanityinc-tomorrow-blue t))
#+end_src

*** Zenburn
This is not a bad theme. ([[https://github.com/bbatsov/zenburn-emacs][GitHub]])

#+begin_src emacs-lisp
  (use-package zenburn-theme
    :ensure t
    :init
    (load-theme 'zenburn t))
#+end_src

I found a few modifications [[https://github.com/bbatsov/zenburn-emacs/issues/350][here]] to make some things a little easier to
read.

#+begin_src emacs-lisp
  (setq zenburn-override-colors-alist
        '(("zenburn-red" . "#de7a78")
          ("zenburn-bg-05" . "#292928")
          ("zenburn-bg" . "#3b3837")))

#+end_src
** Modeline

I think I like [[https://github.com/seagle0128/doom-modeline][doom-modeline]]. It looks really clean.

#+begin_src emacs-lisp
  (use-package doom-modeline
    :ensure t
    :init
    (doom-modeline-mode 1))
#+end_src
** Fonts
* Org Mode
I use Org mode for almost everything.

#+begin_src emacs-lisp
  (setq org-startup-indented t)
  (setq org-log-done 'time)
#+end_src

** Todo
I used to have a =STARTED= keyword in the list, but I never really used it. I
think the current list is fine, although I'm considering adding =NEXT= to it.

#+begin_src emacs-lisp
  (setq org-todo-keywords
          '((sequence "TODO(t)"
                      "WAITING(w)"
                      "|"
                      "DONE(d)"
                      "CANCELLED(c)")))
#+end_src
** Capture
I have a template that allows me to quickly capture tasks to my GTD inbox.

#+begin_src emacs-lisp
  (setq org-capture-templates '(("t" "Todo [inbox]" entry
                                 (file+headline "~/org/gtd/inbox.org" "Tasks")
                                 "* TODO %i%?")))
#+end_src

Since I capture to the inbox frequently, it makes sense to have a function for
this that I can map to a key chord. (I got this from [[https://www.labri.fr/perso/nrougier/GTD/index.html][here]].)

#+begin_src emacs-lisp
  (defun org-capture-inbox ()
    (interactive)
    (call-interactively 'org-store-link)
    (org-capture nil "t"))
#+end_src

Key mappings related to org-capture.

#+begin_src emacs-lisp
  (define-key global-map (kbd "C-c c") 'org-capture)
  (define-key global-map (kbd "C-c i") 'org-capture-inbox)
#+end_src

** Refiling
Refile should always be done either to the projects file or to the 
someday/maybe list.

#+begin_src emacs-lisp
  (setq org-refile-targets '(("~/org/gtd/projects.org" :maxlevel . 3)
                             ("~/org/gtd/someday.org" :level . 1)))
#+end_src

** Agenda
The agenda should remind me of things in the inbox and the projects file.

#+begin_src emacs-lisp
  (setq org-agenda-files '("~/org/gtd/inbox.org"
                           "~/org/gtd/projects.org"))
#+end_src

* Terminal Emulation
** Vterm
Normally I use ansi-term, but I decided to give vterm a go. So far, so good.

#+begin_src emacs-lisp
  (use-package vterm
    :ensure t)
  (global-set-key (kbd "<s-return>") 'vterm)
#+end_src

* Development
** Text Completion

Company mode allows for autocompletion.

#+begin_src emacs-lisp
  (use-package company
    :ensure t
    :init
    (global-company-mode))
#+end_src

** Revision Control

Magit is amazing!

#+begin_src emacs-lisp
  (use-package magit
    :ensure t)
#+end_src

** Project Management
** Programming Languages
*** COMMENT C
I use the Linux style for formatting C code.

#+begin_src emacs-lisp
  (setq c-default-style "linux")
#+end_src
*** Go
*** Python
** Web Development

* Living in Emacs
** Accounting

I use ledger mode to allow me to edit ledger files from Emacs and to generate
reports.

#+begin_src lisp
  (use-package ledger-mode
    :ensure t
    :init
    (setq ledger-clear-whole-transactions 1)
    :mode "\\.ledger\\'")
#+end_src






* TODO CLEAN UP
** User interface
#+BEGIN_SRC emacs-lisp
    
    ;;(load-theme 'wheatgrass t)
    ;;(use-package zenburn-theme
    ;;  :ensure t
    ;;  :init
    ;;  (load-theme 'zenburn t))

    (set-language-environment "UTF-8")
    ;(global-hl-line-mode t)
    ;(global-prettify-symbols-mode t)

  (setq display-time-default-load-average nil)
  (setq display-time-24hr-format t)
  (display-time-mode t)
#+END_SRC
** Fonts
#+BEGIN_SRC emacs-lisp
  (set-face-attribute 'default nil :font "DejaVu Sans Mono")
  (set-fontset-font t 'latin "Noto Sans")
  (set-fontset-font t 'chinese-gbk
                    (font-spec :family "Noto Sans CJK SC"))
  (set-fontset-font t 'japanese-jisx0213.2004-1
                    (font-spec :family "Noto Sans CJK JP"))
  (set-fontset-font t 'hangul
                    (font-spec :family "Noto Sans CJK KR"))
#+END_SRC
** Buffers and windows
#+BEGIN_SRC emacs-lisp
  (use-package ace-window
    :ensure t
    :init
    (progn
      (global-set-key [remap other-window] 'ace-window)
      (custom-set-faces
       '(aw-leading-char-face
         ((t (:inherit ace-jump-face-foreground :height 3.0)))))))
#+END_SRC
** Ansi term
#+begin_src emacs-lisp
  (defvar my-term-shell "/bin/bash")
  (defadvice ansi-term (before force-bash)
    (interactive (list my-term-shell)))
  (ad-activate 'ansi-term)
  ;; (global-set-key (kbd "<s-return>") 'ansi-term)
#+end_src
** Swiper
#+BEGIN_SRC emacs-lisp
  (use-package counsel
    :ensure t)

  (use-package swiper
    :ensure t
    :config
    (progn
      ;; Copied and yanked from the Swiper doc for now.
      (ivy-mode 1)
      (setq ivy-use-virtual-buffers t)
      (setq enable-recursive-minibuffers t)
      ;; enable this if you want `swiper' to use it
      ;; (setq search-default-mode #'char-fold-to-regexp)
      (global-set-key "\C-s" 'swiper)
      (global-set-key (kbd "C-c C-r") 'ivy-resume)
      (global-set-key (kbd "<f6>") 'ivy-resume)
      (global-set-key (kbd "M-x") 'counsel-M-x)
      (global-set-key (kbd "C-x C-f") 'counsel-find-file)
      (global-set-key (kbd "<f1> f") 'counsel-describe-function)
      (global-set-key (kbd "<f1> v") 'counsel-describe-variable)
      (global-set-key (kbd "<f1> l") 'counsel-find-library)
      (global-set-key (kbd "<f2> i") 'counsel-info-lookup-symbol)
      (global-set-key (kbd "<f2> u") 'counsel-unicode-char)
      (global-set-key (kbd "C-c g") 'counsel-git)
      (global-set-key (kbd "C-c j") 'counsel-git-grep)
      (global-set-key (kbd "C-c k") 'counsel-ag)
      (global-set-key (kbd "C-x l") 'counsel-locate)
      (global-set-key (kbd "C-S-o") 'counsel-rhythmbox)
      (define-key minibuffer-local-map (kbd "C-r") 'counsel-minibuffer-history)))
#+END_SRC
** Key bindings
#+BEGIN_SRC emacs-lisp
(global-set-key [C-mouse-4] 'text-scale-increase)
(global-set-key [C-mouse-5] 'text-scale-decrease)
#+END_SRC

** Powerline
#+BEGIN_SRC emacs-lisp
    ;; (use-package powerline
    ;;  :ensure t)
    ;; (powerline-default-theme)
#+END_SRC

** Org-drill
#+BEGIN_SRC emacs-lisp
  (use-package org-drill
    :ensure t)
  (setq org-drill-add-random-noise-to-intervals-p t)
  (setq org-drill-scope 'directory)
  (setq org-drill-learn-fraction 0.4)
  (setq org-drill-maximum-items-per-session 50)
  (setq org-drill-maximum-duration 30)
#+END_SRC
** Babel
#+begin_src lisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((ledger . t)))

#+end_src

** Company
#+BEGIN_SRC emacs-lisp
  ; (use-package company-go
  ;  :ensure t)
#+END_SRC
** Yasnippet
#+BEGIN_SRC emacs-lisp
  (use-package yasnippet
    :ensure t
    :init
    (yas-global-mode 1))
  (add-to-list 'load-path "~/.emacs.d/plugins/yasnippet")
#+END_SRC

** Projectile
#+begin_src emacs-lisp
  (use-package projectile
    :ensure t
    :config
    (define-key projectile-mode-map (kbd "s-p") 'projectile-command-map)
    (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
    (projectile-mode +1))
#+end_src
** Treemacs
#+begin_src emacs-lisp
  ;; copied from treemacs documentation. I should find time and go through this at
  ;; some point

  (use-package treemacs
    :ensure t
    :defer t
    :init
    (with-eval-after-load 'winum
      (define-key winum-keymap (kbd "M-0") #'treemacs-select-window))
    :config
    (progn
      (setq treemacs-collapse-dirs                 (if treemacs-python-executable 3 0)
            treemacs-deferred-git-apply-delay      0.5
            treemacs-directory-name-transformer    #'identity
            treemacs-display-in-side-window        t
            treemacs-eldoc-display                 t
            treemacs-file-event-delay              5000
            treemacs-file-extension-regex          treemacs-last-period-regex-value
            treemacs-file-follow-delay             0.2
            treemacs-file-name-transformer         #'identity
            treemacs-follow-after-init             t
            treemacs-git-command-pipe              ""
            treemacs-goto-tag-strategy             'refetch-index
            treemacs-indentation                   2
            treemacs-indentation-string            " "
            treemacs-is-never-other-window         nil
            treemacs-max-git-entries               5000
            treemacs-missing-project-action        'ask
            treemacs-no-png-images                 nil
            treemacs-no-delete-other-windows       t
            treemacs-project-follow-cleanup        nil
            treemacs-persist-file                  (expand-file-name ".cache/treemacs-persist" user-emacs-directory)
            treemacs-position                      'left
            treemacs-recenter-distance             0.1
            treemacs-recenter-after-file-follow    nil
            treemacs-recenter-after-tag-follow     nil
            treemacs-recenter-after-project-jump   'always
            treemacs-recenter-after-project-expand 'on-distance
            treemacs-show-cursor                   nil
            treemacs-show-hidden-files             t
            treemacs-silent-filewatch              nil
            treemacs-silent-refresh                nil
            treemacs-sorting                       'alphabetic-asc
            treemacs-space-between-root-nodes      t
            treemacs-tag-follow-cleanup            t
            treemacs-tag-follow-delay              1.5
            treemacs-user-mode-line-format         nil
            treemacs-width                         35)

      ;; The default width and height of the icons is 22 pixels. If you are
      ;; using a Hi-DPI display, uncomment this to double the icon size.
      ;;(treemacs-resize-icons 44)

      (treemacs-follow-mode t)
      (treemacs-filewatch-mode t)
      (treemacs-fringe-indicator-mode t)
      (pcase (cons (not (null (executable-find "git")))
                   (not (null treemacs-python-executable)))
        (`(t . t)
         (treemacs-git-mode 'deferred))
        (`(t . _)
         (treemacs-git-mode 'simple))))
    :bind
    (:map global-map
          ("M-0"       . treemacs-select-window)
          ("C-x t 1"   . treemacs-delete-other-windows)
          ("C-x t t"   . treemacs)
          ("C-x t B"   . treemacs-bookmark)
          ("C-x t C-t" . treemacs-find-file)
          ("C-x t M-t" . treemacs-find-tag)))

  (use-package treemacs-projectile
    :after treemacs projectile
    :ensure t)

  (use-package treemacs-icons-dired
    :after treemacs dired
    :ensure t
    :config (treemacs-icons-dired-mode))

  (use-package treemacs-magit
    :after treemacs magit
    :ensure t)
#+end_src

** Programming
*** Go
#+BEGIN_SRC emacs-lisp
  (use-package go-mode
    :ensure t
    :config
    (add-hook 'before-save-hook 'gofmt-before-save))
#+END_SRC
*** Python
#+BEGIN_SRC emacs-lisp
  (use-package python
    :ensure nil)
    ; :hook
    ; ((python-mode . jedi:setup)))

  (use-package pyvenv
    :ensure t
    :config
    (pyvenv-mode 1))

  ; (use-package company-jedi
  ;  :ensure t
  ;  :config
  ;  (add-to-list 'company-backends 'company-jedi))

  ; (use-package elpy
  ;  :ensure t
  ;  :init
  ;  (elpy-enable))

  (when (executable-find "ipython")
    (setq python-shell-interpreter "ipython"
          python-shell-interpreter-args "--simple-prompt -i"))
#+END_SRC

*** TODO automaticall install required packages in virtual environment [0/4]
- [ ] flake8
- [ ] autopep8
- [ ] jedi (is this needed?)
- [ ] yapf
*** Web-mode
#+begin_src emacs-lisp
  (use-package web-mode
    :ensure t
    :mode (".html?$")
    :config
    (setq
     web-mode-enable-engine-detection t
     web-mode-markup-indent-offset 2
     web-mode-css-indent-offset 2
     web-mode-code-indent-offset 2
     web-mode-enable-auto-closing t
     web-mode-enable-auto-opening t
     web-mode-enable-auto-indentation t))

  ;; https://emacs.stackexchange.com/questions/32585/set-web-mode-engine-per-directory
  (defun lorenzo/django-engine ()
    (if (projectile-project-p)
        (if (file-exists-p (concat (projectile-project-root) "manage.py"))
            (web-mode-set-engine "django"))))
  (add-hook 'web-mode-hook 'lorenzo/django-engine)
#+end_src
** Docker
#+BEGIN_SRC emacs-lisp
  (use-package dockerfile-mode
    :ensure t
    :init
    (add-to-list 'auto-mode-alist '("Dockerfile\\'" . dockerfile-mode)))
#+END_SRC 
** EMMS
#+BEGIN_SRC emacs-lisp
  (use-package emms
    :ensure t
    :config
    (progn
      (emms-standard)
      (emms-default-players)
      (setq emms-playlist-buffer-name "EMMS")
      (setq emms-source-file-default-directory "~/musica/")))

  (use-package org-emms
    :ensure t)
#+END_SRC
** Elfeed
#+BEGIN_SRC emacs-lisp
  (use-package elfeed
    :ensure t)
  (global-set-key (kbd "C-x w") 'elfeed)

  (use-package elfeed-org
    :ensure t
    :init
    (elfeed-org))
  (setq rmh-elfeed-org-files (list "~/org/feeds.org"))
#+END_SRC
** Matrix-client
#+begin_src emacs-lisp
  (use-package matrix-client
    :quelpa (matrix-client
             :fetcher github
             :repo "alphapapa/matrix-client.el"
             :files (:defaults "logo.png" "matrix-client-standalone.el.sh")))
#+end_src
** PDF Tools
#+begin_src emacs-lisp
  (use-package pdf-tools
    :ensure t
    :config
    (pdf-tools-install)
    (setq-default pdf-view-display-size 'fit-page))

  (use-package org-pdfview
    :ensure t)
#+end_src
** Pass
#+begin_src emacs-lisp
  (use-package pass
    :ensure t)
#+end_src
** TODO configuration [4/5]                                      :@computer:
- [X] set up fonts [3/3]
  - [X] Korean
  - [X] Japanese
  - [X] Chinese
- [X] keybindings to zoom in/zoom out
- [ ] follow links by hitting enter
- [X] don't ask which shell to run in =term=
- [X] install which-key package

